name: Kubernetes Validate

on:
  push:
    paths:
      - 'k8s/**'
  pull_request:
    paths:
      - 'k8s/**'

jobs:
  k8s-validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install kubeconform
      run: |
        wget https://github.com/yannh/kubeconform/releases/download/v0.6.4/kubeconform-linux-amd64.tar.gz
        tar xf kubeconform-linux-amd64.tar.gz
        sudo mv kubeconform /usr/local/bin/
        
    - name: Validate Kubernetes Manifests
      run: |
        kubeconform -summary k8s/
